### ISSUE TITLE
Not able to add gradle dependency

### ISSUE THREAD

**Issue by sc231997** [adityagohad/HorizontalPicker#2]
when i added the dependency in built.gradle(app) then following error is shown :

Error:(27, 13) Failed to resolve: com.github.adityagohad:HorizontalPicker:1.0.0

**Comment by adityagohad** [comment]
Hey there was some weird jitpack issue I was facing

I have created new version v1.0.1 so try new one now
by adding 
```
compile 'com.github.adityagohad:HorizontalPicker:1.0.1'
```
to your gradle file.

Also don't forget to add 
```
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
```

**Comment by sc231997** [comment]
thanks for help.

hi i need one more help. i want to set a default value for the picker so
that whenever app is run the picker have that value.

**Comment by adityagohad** [comment]
recyclerView.smoothScrollToPosition(<your_position>);
